# Codecov Configuration
# https://docs.codecov.com/docs/codecov-yaml

codecov:
  require_ci_to_pass: yes
  notify:
    wait_for_ci: yes

coverage:
  precision: 2
  round: down
  range: "15...80"
  
  status:
    project:
      default:
        # Required coverage for the entire project
        target: auto
        threshold: 2%
        # Don't fail if coverage drops by less than 2%
        if_not_found: success
        
    patch:
      default:
        # Required coverage for changed lines
        target: 60%
        threshold: 5%
        if_not_found: success

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment:
  layout: "reach,diff,flags,files,footer"
  behavior: default
  require_changes: no
  require_base: no
  require_head: yes
  
flags:
  unit-tests:
    paths:
      - apps/api/src/
    carryforward: true
    
  e2e-tests:
    paths:
      - apps/api/src/
    carryforward: true

ignore:
  - "**/*.spec.ts"
  - "**/*.test.ts"
  - "**/test/**"
  - "**/tests/**"
  - "**/*.dto.ts"
  - "**/*.module.ts"
  - "**/main.ts"
  - "**/node_modules/**"
  - "**/dist/**"
  - "**/.next/**"
